### ISSUE TITLE
Upload seemingly doesn't work - UI/UX issue

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fairdrive-theapp#100]
Uploading a file doesnt work when there is no pod selected. Which makes sense from a technical point of view.
But for a first-time end user creating and account and trying out the dapp, it feels like the dapp isn't working at all.

Either 

1.  the Upload button should be displayed only when a pod is selected
2. or even better from a UX point of view - file should be uploaded to default pod ("Home" for eg) if no pod is selected

![image](https://user-images.githubusercontent.com/520570/174138521-08c955eb-5877-42e7-af37-fa656e455b84.png)

**Comment by crtahlin** [comment]
Please verify behavior and implement variant described under (1):
1. the Upload button should be displayed only when a pod is selected

**Comment by molekilla** [comment]
Pending PR merge with latest `fdp-storage` v0.3.0 https://github.com/fairDataSociety/fairdrive-theapp/issues/101

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fairdrive-theapp/100?planning-poker) with ZenHub @tfius @molekilla

**Comment by molekilla** [comment]
Pull request with bug fix
https://github.com/fairDataSociety/fairdrive-theapp/pull/118
