### ISSUE TITLE
Integrate new login flow in Fairdrive

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#101]

**Comment by molekilla** [comment]
@jayolin https://github.com/fairDataSociety/fairdrive-theapp/pull/102 can you complete this PR comments so we can merge?

**Comment by jayolin** [comment]
Okay. On it

**Comment by tfius** [comment]
waiting for PR https://github.com/fairDataSociety/fairdrive-theapp/pull/102

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fairdrive-6266aaec4367e80011e0c3c5/issues/fairDataSociety/fairdrive-theapp/101?planning-poker) with ZenHub @molekilla @tfius

**Comment by tfius** [comment]
move register, migrate to create-account,  only implement login

**Comment by crtahlin** [comment]
Duplicate of https://github.com/fairDataSociety/fairdrive-theapp/issues/134
