### ISSUE TITLE
Review rewrite of Readme file

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#104]
Review PR for Readme file
https://github.com/fairDataSociety/fairdrive-theapp/blob/6618c33172088938d74fda9d469c8d957419b3d1/README.md

**Comment by crtahlin** [comment]
@molekilla the below link isn't a pull request, to be review; something is not ok? 
https://github.com/fairDataSociety/fairdrive-theapp/blob/6618c33172088938d74fda9d469c8d957419b3d1/README.md

**Comment by molekilla** [comment]
this was in the last PR Merged to development. In that case, open if we
need to review we can do another PR

**Comment by tfius** [comment]
this was reviewed
