### ISSUE TITLE
Implement mobile friendly Fairdrive app

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#112]
Implement mobile friendly Fairdrive app  - css styles and whatever else needs to be done.

**Comment by molekilla** [comment]
@crtahlin I think we bumped theapp to latest nextjs, the thing would be changing the themes to a responsive

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fairdrive-6266aaec4367e80011e0c3c5/issues/fairDataSociety/fairdrive-theapp/112?planning-poker) with Zenhub @molekilla @tfius

**Comment by tfius** [comment]
going away from this ![image](https://user-images.githubusercontent.com/1674145/186430470-5d796385-c149-4ba0-bf08-47623fd9441b.png)

**Comment by tfius** [comment]
![image](https://user-images.githubusercontent.com/1674145/186431526-277e69ed-e74b-41dc-9bd9-bec6424dcbde.png)

**Comment by tfius** [comment]
![image](https://user-images.githubusercontent.com/1674145/186431579-7ee4bf54-678f-4f5e-92a4-345e43f067e4.png)

**Comment by tfius** [comment]
![image](https://user-images.githubusercontent.com/1674145/186431624-08c37fd7-8aa7-4914-963e-e8ecbd45fb8c.png)

**Comment by crtahlin** [comment]
@crtahlin add link to Figma file with designs.

**Comment by crtahlin** [comment]
Figma design file: https://www.figma.com/file/gjGqOHWfdfz3oU6eGo4Adu/Fairdrive-Style-Guide-Sharing-V0.2.0

**Comment by IgorShadurin** [comment]
@crtahlin can be closed?
We have made significant progress with working on mobile devices, so I think we can close

**Comment by crtahlin** [comment]
Sure, if @tfius is in agreement.

**Comment by tfius** [comment]
Much progress has been made on mobile friendliness.
