### ISSUE TITLE
Is this a PWA ?

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fairdrive-theapp#116]
We should check, once we have mobile theme ready, that this app is Progressive Web App, so we can use it from
as desktop icons on mobiles. @molekilla

**Comment by molekilla** [comment]
Implement `nextjs-pwa`

**Comment by molekilla** [comment]
Implement `nextjs-pwa`

**Comment by tfius** [comment]
found example here https://github.com/vercel/next.js/tree/canary/examples/progressive-web-app

**Comment by tfius** [comment]
added nextjs-pwa
