### ISSUE TITLE
Fairdrive pods do not refresh shown content when switched

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#119]
As visible in the animated GIF:

![Fairdrive-pods-do-not-refresh.gif](https://images.zenhubusercontent.com/5dd2b5cb40c01dbae3b2e18b/b359edb4-15fe-4588-8950-c767788e654f)

Or they do so very "slowly". 

Expected result: the shown contents refresh within 1 second.
Minimum expected result: when switching a pod, the shown content is cleared, so that a blank page is shown, before everything is loaded. Otherwise we have the impression we are still browsing the previous pod.

**Comment by molekilla** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/pull/130
