### ISSUE TITLE
Blockie icon changes with each login

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#120]
See GIF recording:

![Blockie-identity-icon-changes-with-login](https://user-images.githubusercontent.com/1554520/187211265-f09a1878-e1d8-45bc-a4d7-9dadaa3e7e16.gif)

Expected behavior: blockie icon should represent user's identity and should not change. So with each login, it should be same.

**Comment by molekilla** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/pull/137

**Comment by tfius** [comment]
closed with #137
