### ISSUE TITLE
After new login flow implemented remove "exporting" of users

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#121]
see screenshot:

![image](https://user-images.githubusercontent.com/1554520/187230443-10d86dfb-3763-45b0-a66f-e7ab81674002.png)

With the new SSO login, user's will no longer be "moved" between FairOS servers and the export feature does not make sense.
It could be left the for a 2 month period with a "(deprecated)" next to the button. Or just removed entirely immediately.

**Comment by molekilla** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/pull/131

**Comment by crtahlin** [comment]
merged, closing
