### ISSUE TITLE
Uploading two files with same name results in strange naming of the second file

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#123]
See animated GIF:

![Upload-existing-file](https://user-images.githubusercontent.com/1554520/187263259-6cc86f93-12fc-4063-be0c-d971d4d7914e.gif)

Expected result: warning that file already exists and an option to "Cancel", "Overwrite" or "Save as ..."

**Comment by teardrop** [comment]
This bug is fixed, the error message will need to be improved

<img width="1466" alt="Cursor_and_Fairdrive" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/898007/ec51a654-3fe0-4bb2-8613-487cc873fdfd">
