### ISSUE TITLE
Implement escaping submenu of file

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#125]
See animated GIF:

![Cannot-Escape-submenu](https://user-images.githubusercontent.com/1554520/187265178-15a06d31-017c-4210-9a29-00d961820a4d.gif)

When user clicks menu button next to a file, they cannot escape the menu unless they again click the same button.

Expected behavior:
Escaping the menu should be possible with the Escape button or just by clicking outside of the submenu.

**Comment by teardrop** [comment]
Clicking any

https://github.com/fairDataSociety/fairdrive-theapp/assets/898007/c41d6c83-f393-4860-9d6d-d7eeb24b8346

where outside the menu or modal windows will close the menu/modal now
