### ISSUE TITLE
Clicking to Open a file does not open it

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#126]
See animated GIF:

![Clicking-open-does-not-open](https://user-images.githubusercontent.com/1554520/187266007-d3382a41-3199-4672-9856-2d4c8e148117.gif)

Current behavior:
Clicking on a file open a preview sidebar, which is OK.
Clicking specifically on "Open" in the submenu also opens the sidebar. This is not expected behavior.

Expected behavior:
Clicking on "Open" should directly open a file in an appropriate registered app (e.g. Dracula for Markdown). If no app is registered, it should either ask which app to use or at least make the option to "Open" unavailable.

**Comment by IgorShadurin** [comment]
"Open" has been removed
