### ISSUE TITLE
Upgrade for FDP storage support

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#134]

**Comment by molekilla** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/pull/136/files

**Comment by molekilla** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/pull/139

**Comment by molekilla** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/pull/154

**Comment by crtahlin** [comment]
implemented, closing
