### ISSUE TITLE
Faridrive (dev) cannot list pods

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#138]
See screenshot:

![image](https://user-images.githubusercontent.com/1554520/188583207-22857746-1ac2-4e11-88a4-aefe97f50051.png)

User: fairos-demouser
Should have at least one pod present.

Possibly sth related to cookies and calls to FairOS.

**Comment by molekilla** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/pull/139

**Comment by crtahlin** [comment]
verified on development, closing
