### ISSUE TITLE
Cannot upload to root of pod

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#143]
Version after change to fdp-storage does not allow uploading to "root" of Pod:

![image](https://user-images.githubusercontent.com/1554520/188718843-329d1e2e-0ab0-4fba-9394-080ac93d2d1f.png)

**Comment by molekilla** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/pull/154

**Comment by crtahlin** [comment]
solved, closing
