### ISSUE TITLE
Make light theme available in Fairdrive

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#16]
After #15 is done, light theme should be available in Fairdrive app, by user switching a toggle button.

**Comment by crtahlin** [comment]
When closing, please refer to commit and where the update is available, to test.

**Comment by mmahmutovic** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/commit/32ca9b0a382bf7080ba72b14dcb5080d84eda1ef

update is available on https://app.fairdrive.fairdatasociety.org/
Switching theme is icon on top right corner. As shown on screenshot 
<img width="1323" alt="Screenshot 2021-07-02 at 12 06 17" src="https://user-images.githubusercontent.com/75730861/124258678-f841b880-db2d-11eb-87b1-79b9bfb381e9.png">
