### ISSUE TITLE
Fix black theme 

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fairdrive-theapp#187]
![image](https://user-images.githubusercontent.com/1674145/198638408-14bbe5a2-7d8f-466b-ac28-685b707d393c.png)
text in background is not being seen

**Comment by teardrop** [comment]
For as much as I tested, this was fixed.
The only issue that remains is that the /register page doesn't have a dark mode and we'll need to make sure text remains visible there, once we fix this
