### ISSUE TITLE
Special Build

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fairdrive-theapp#192]
We need to create a build that instantiates Swarm mainnet (bee) and uses ENS from goerli. This can be done with proper constructor options. We want to test speed on mainnet network and not wait for mainnet ens integration.

Maybe @nugaon can give more detail what options should be used ?

**Comment by nugaon** [comment]
what detail is needed?
the corresponding Bee client of the `BEE_API_URL` should connect to the mainnet.
```
new FdpStorage(BEE_API_URL, BEE_BATCH_ID, options)
```
