### ISSUE TITLE
Add to disclaimer notice for autodeployed version

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#20]
After #19 is done, make the version on the autodeployment branch slightly different from the one on the master branch. 

To the disclaimer on the top add "NOTE: This version is by default configured to run on testnet."

Also, make the config files reflect that fact, that it is on testnet.

**Comment by teardrop** [comment]
Kamino cloned this issue to [teardrop/Fairdrive](https://github.com/teardrop/Fairdrive/issues/18)
