### ISSUE TITLE
License file missing?

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fairdrive-theapp#210]
What license does the fairdrive repo use?

**Comment by crtahlin** [comment]
There was license file way back in 2020 (https://github.com/fairDataSociety/fairdrive-theapp/tree/feature/removing-app-folder). Not sure if it was removed or what happened? 

The same as this was supposed to be used:
https://github.com/fairDataSociety/fds.js/blob/master/COPYING
Though we might reexamine the specific licence to use, if needed.

@tomicvladan can we find out what happened with the LICENSE file? 

Afterwards, please re-add it.

**Comment by tomicvladan** [comment]
The file was deleted in this commit: https://github.com/fairDataSociety/fairdrive-theapp/commit/17e7e8ca9809397df3aa386ed27ca1d0fa25739b

Here is the PR that returns it: https://github.com/fairDataSociety/fairdrive-theapp/pull/212

**Comment by crtahlin** [comment]
@tomicvladan @tfius is this by chance also the commit that implemented next-js instead of the react "router"?

**Comment by tomicvladan** [comment]
Yes, it seems so. Judging by the `package.json` file in the commit, the `next` dependencies were added that didn't exist before.
