### ISSUE TITLE
Uploading a file throws error - "File could not be uploaded"

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fairdrive-theapp#220]
Please verify behavior and implement variant described under (1):
1. the Upload button should be displayed only when a pod is selected

_Originally posted by @crtahlin in https://github.com/fairDataSociety/fairdrive-theapp/issues/100#issuecomment-1211883486_

**Comment by rampall** [comment]
This issue still exists. 
Steps:

1 - go to https://app.fairdrive.fairdatasociety.org/
2 - enter username and password and click "continue"
3 - once logged in to overview: click "go to drive"
4 - once in "inventory" page: click "upload" button
5 - drag and drop any file onto the sidebar and click "upload content" 

![image](https://user-images.githubusercontent.com/520570/203615017-41318392-3988-4bb5-849f-d37a6dfa899c.png)

**Comment by crtahlin** [comment]
@tfius please triage and assign to relevant person.
