### ISSUE TITLE
In "Explore DApps" page, the NFTGenerator DApp has no link

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fairdrive-theapp#221]
![image](https://user-images.githubusercontent.com/520570/203616357-11acbbde-a98a-4ccf-b90b-59bfbeff8d26.png)

**Comment by crtahlin** [comment]
This would probably be solved with deploying the version currently in the works to mainnet. Pls check after that is done and close or fix if not, @tomicvladan

**Comment by rampall** [comment]
Closing as this has been fixed since.
