### ISSUE TITLE
footer swarm logo change to current

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fairdrive-theapp#238]
![Horizontal_Black](https://user-images.githubusercontent.com/81620050/210560011-53053660-f18d-4b51-b58d-834131d6210b.svg)

**Comment by IgorShadurin** [comment]
@tamas6 still relevant?

### Current version
<img width="1162" alt="Screenshot 2023-09-08 at 15 19 34" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/1595061/e0431bdd-b544-46c2-86a8-0973896faac4">

**Comment by tamas6** [comment]
> @tamas6 still relevant?
> 
> ### Current version
> <img alt="Screenshot 2023-09-08 at 15 19 34" width="1162" src="https://user-images.githubusercontent.com/1595061/266608752-e0431bdd-b544-46c2-86a8-0973896faac4.png">

typo changed but logo remained, so still relevant
