### ISSUE TITLE
Menu click bug

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#25]
Case 1
1) Click by menu on folder
2) Instead of opening a menu, a folder opens

Case 2
1) Click by menu on file
2) Instead of opening a menu, a preview opens
3) Click somewhere, preview closes, but menu not closes

https://user-images.githubusercontent.com/1595061/124355414-a37b6c00-dc19-11eb-92ca-a4f81d74e933.mov

**Comment by mmahmutovic** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/commit/53f31ae4e85886c8105549eeae6e33ad994ef503


This merge closes the menu bug
