### ISSUE TITLE
cannot login using blossom new account  - fdp-play

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fairdrive-theapp#257]
## environment:
latest master branches
docker, fdp-play obviously running

## replicate:
fairdrive: try entering a random word as username, and random password, it will give a "Username "test" does not exists"

if you make a local fdp-play account (with any password) on blossom with the the same username you just tried, fairdrive will tell "Wrong password" even tho you entered the correct pw what is currently let u logged into blossom extension.

@tomicvladan brave enough to take care of this

**Comment by tomicvladan** [comment]
This is no more relevant.
