### ISSUE TITLE
Create pod bug

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#26]
1) Create pod
2) Check http requests. Instead of calling `pod/new` calls `pod/receive`

https://user-images.githubusercontent.com/1595061/124355617-c4908c80-dc1a-11eb-8aa3-38413dbd3f54.mov

**Comment by mmahmutovic** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/commit/2382862d729d1036d76882aea9dccd5e2c8bc3cb
