### ISSUE TITLE
UI defect on creating new pod

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#27]
1) Click by "Create Pod"
2) Text on "Create" button too small

<img width="1655" alt="Screenshot 2021-07-03 at 16 25 12" src="https://user-images.githubusercontent.com/1595061/124355711-513b4a80-dc1b-11eb-9244-2dd3610c0cfd.png">

**Comment by mmahmutovic** [comment]
![Screenshot 2021-07-06 at 14 11 17](https://user-images.githubusercontent.com/75730861/124598184-a322e100-de64-11eb-9acb-00a39b7742dd.png)
