### ISSUE TITLE
No error with invalid credentials

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#28]
1) Try login with invalid credentials
2) Nothing happens

Expected:
Displaying error message

**Comment by mmahmutovic** [comment]
![Screenshot 2021-07-09 at 11 01 48](https://user-images.githubusercontent.com/75730861/125053272-364a5980-e0a5-11eb-8755-7311a6097fa4.png)


https://github.com/fairDataSociety/fairdrive-theapp/commit/544681e057eef5b45e6595e21701deee19f95847


Added feedback on login
