### ISSUE TITLE
Revise text under "Get started with your Drive"

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#283]
The text is "Start interacting with the Fairtext in Fairdrive, create your Subpods and explore new ways to organize your files."

What is "Fairtext"? "Subpods"?

<img width="671" alt="Screenshot 2023-03-29 at 12 33 04" src="https://user-images.githubusercontent.com/1595061/228492002-b778c3d7-46c9-4b98-9c5c-c4a23e83f522.png">

**Comment by crtahlin** [comment]
Please change text to:
"Start interacting with dApps in Fairdrive, create pods and folders and explore a decentralized storage solution for your files."
