### ISSUE TITLE
File and directory menu headers appear clickable but are not functional

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#287]
**Description**
The file menu and directory menu headers appear to be clickable, like other action items within the context of the menu. However, they are not functional and do not perform any action upon clicking.

To improve user experience, it is suggested to modify their text to distinguish to more neutral like Menu or Actions.

**Steps to Reproduce**
Open the file menu or directory menu.
Try clicking on the menu headers.
Expected Behavior
The headers should either be clearly distinguishable as non-clickable items or should perform a specific action when clicked.

**Actual Behavior**
The headers appear to be clickable options, but they do not perform any action upon clicking, which can confuse users.

**Possible Solution**
Modify the text of the headers to make them context distinct from other clickable options.

<img width="1164" alt="Screenshot 2023-04-06 at 15 17 02" src="https://user-images.githubusercontent.com/1595061/230379252-224ee93c-6d86-46f5-aff5-9dd808b2b1b9.png">

**Comment by tfius** [comment]
Should be done as on mobile version probably
