### ISSUE TITLE
Warning message appears after agreed

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#29]
1) Open main page
2) Click by "Ok, I Agree!"
3) Reload page, message appears

Expected:
Message not appears
<img width="1065" alt="Screenshot 2021-07-04 at 11 41 45" src="https://user-images.githubusercontent.com/1595061/124378944-efcbb800-dcbc-11eb-88b3-6baa1b1a9dd4.png">

**Comment by AngelaVitzthum** [comment]
UI has changed so that user no longer has to take action on the CTA. Closing out.
