### ISSUE TITLE
Is ExportUserModal needed?

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#297]
Looks like `ExportUserModal` in `src/components/Modals/ExportUserModal/ExportUserModal.tsx` is never using, but it makes api calls on initialization.

I suppose it could be removed/disabled.

Do we need it? @tomicvladan

**Comment by tomicvladan** [comment]
I think this was used in period of transition from v1 to v2. I think we can delete it now.
