### ISSUE TITLE
File name is out of bounds in preview mode

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#307]
File name is out of bounds in preview mode.

<img width="761" alt="Screenshot 2023-04-12 at 14 11 10" src="https://user-images.githubusercontent.com/1595061/231442925-bd818cd8-90db-4759-b704-83ccf56c5ee9.png">

**Comment by tfius** [comment]
can be smaller font size, same as "File size" and not bold
