### ISSUE TITLE
Use blockie for person avatar

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#31]
For the image of the user, generate a blockie avatar, as is done in Ethereum wallets. 

E.g., using: https://github.com/cryptohub-digital/blockies

**Comment by crtahlin** [comment]
Explore this option, it makes sense if access to public key is possible.

**Comment by mmahmutovic** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/commit/f64de71a692c7dfd2a9a9c629a172952c761ec46
