### ISSUE TITLE
Styles problem on dev version

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#312]
The version of the app looks a bit strange. As if it missed some CSS (but no errors in the console).

Deployed dev version https://app.fairdrive.dev.fairdatasociety.org/
<img width="1723" alt="Screenshot 2023-04-19 at 15 31 02" src="https://user-images.githubusercontent.com/1595061/233075713-949edbe1-a95c-498f-87cb-0a70a7cbe093.png">

Local dev version
<img width="1728" alt="Screenshot 2023-04-19 at 15 34 34" src="https://user-images.githubusercontent.com/1595061/233076240-4a6f0a7b-e219-45a8-9dd5-fe04ff628179.png">

**Comment by tamas6** [comment]
experience  the same, tried with chrome and safari too

**Comment by tomicvladan** [comment]
@IgorShadurin @tamas6 Could you check it again? Seems some CSS wasn't loaded properly.

**Comment by IgorShadurin** [comment]
Looks good now
