### ISSUE TITLE
.dev.unable to login w/ blossom

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fairdrive-theapp#313]
"Application error: a client-side exception has occurred (see the browser console for more information)."

tested w/ multiple browsers

account is working in FDA, deployed fd and blossom, for several months now.

Behavior:
for a fraction of second the "explore" section is flashed then the blank screen with the oneliner above. 
Logs:
<img width="508" alt="Screenshot 2023-04-19 at 16 00 43" src="https://user-images.githubusercontent.com/81620050/233099086-6eecdea6-8f5e-4766-a249-9e1007cb6639.png">

**Comment by tamas6** [comment]
> The error should be fixed now. Can you check it @tamas6 ?

checked, still not able to login

**Comment by tomicvladan** [comment]
This error has been fixed.
