### ISSUE TITLE
Login with Blossom returns an error when Fairdrive web app should load

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#327]
Using Chromium, Linux, Sward extension, Blossom extension 0.3.1.

Logging into Blossom with account, connecting to Fairdrive, accepting prompt that access should be given. The error is returned as shown on screenshot:

![image](https://user-images.githubusercontent.com/1554520/236786649-0c523a26-9775-431f-9a3c-8e8a88a73499.png)

**Comment by tomicvladan** [comment]
This was a temporary error and not related to Blossom.
