### ISSUE TITLE
Cannot create Pod due to error

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#332]
https://app.fairdrive.fairdatasociety.org/drive, using Blossom login

Trying to create a new pod, called "Consents". An error appers on pop-up, saying "Error: undefined". See screenshot:

![image](https://github.com/fairDataSociety/fairdrive-theapp/assets/1554520/ef701d0f-178d-4d5d-8efa-704f6b66fe0d)

Pod is not created.

**Comment by crtahlin** [comment]
It seems to work now, if I login not using Blossom.

**Comment by tomicvladan** [comment]
I have just tried to create a pod with Blossom and it worked. So it seems that something else caused the issue. @crtahlin have you tried to create a pod with a different name?

**Comment by crtahlin** [comment]
How could that affect behaviour?

@tamas6 can you please check with 2 different accounts, using Blossom, if you can recreate the issue.
