### ISSUE TITLE
Opening menu on mobile version

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#344]
I've noticed a few inconsistencies in our mobile menu behaviour that could benefit from some adjustment.

* Currently, when the menu is opened by tapping, it doesn't close when tapping empty space, which isn't the usual expected behaviour. It seems to only close when tapping on the same file/directory again. This could potentially confuse users and disrupt their workflow.

* I propose we change the default behaviour when tapping on a file or directory. Instead of opening the menu, tapping a directory should open it directly. The options for the menu (like deleting, renaming, etc.) can then be made available on the opened directory page. Similarly, tapping a file should open a preview directly. The options for the file can be made available on the preview page or through a separate menu.

By refining these interactions, I believe we can make our mobile user experience more intuitive and user-friendly.

https://github.com/fairDataSociety/fairdrive-theapp/assets/1595061/7ece6345-7c90-4e23-9d42-5fb06d9c1b3c

**Comment by tomicvladan** [comment]
I vote for bootstrap too, but since Tailwind CSS is used already it's easier to convert to headlessui.
