### ISSUE TITLE
Padding in uploading file modal

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#346]
'Upload File' modal has padding only on the left side. This creates an unbalanced look and feel to the modal.

It would be great if we could either:

* Add the same amount of padding to the right side for consistency, or
* Remove the left padding entirely for a full-width modal.

<img width="529" alt="Screenshot 2023-05-16 at 16 04 02" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/1595061/ffcd4e8b-8157-4212-91cc-7102c9b3879b">

**Comment by tfius** [comment]
<img width="365" alt="Screenshot 2023-07-06 at 16 30 24" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/1674145/522e7258-389f-492c-8203-90a3f237b2ad">

this is still not ok. when uploading, button MUST be disabled, increase space between spinner. button after upload must be enabled back and panel should be ready for new uploade.

**Comment by IgorShadurin** [comment]
@tomicvladan please check @tfius comment
