### ISSUE TITLE
@staging not able to login with newly created sepolia acc.

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fairdrive-theapp#350]
try to **login**: https://fairdrive.staging.fairdatasociety.org/
prompt message: "Username testmehere (edit: or other) does not exist"

**created** at https://create.staging.fairdatasociety.org/#/register
same credentials used at may 22nd, and later may 24th to _seemingly_ succesfully create 

account creation gave feedback that transaction  was sucsessful and then after 2 mins I  tried to login

testmehere
pswrd: testmehere1234

**Comment by tomicvladan** [comment]
I think we resolved this. The issue was in insufficient funds for created account.
