### ISSUE TITLE
Explore when and how Restore/import user from seed phrase

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#36]
If it makes sense in the Fairdrive app at all - when would such a restore make sense? Will usernames and passwords persist if we move to another FairOS instance?

**Comment by IgorShadurin** [comment]
@crtahlin user restore make sense when user connect to other FairOS instance where user previously not logged in. User will get an access to his data if two FairOS instances connected to one network. 
But if we will integrate login system based on blockchain, recover via seed phrase wouldn’t be required, as all required data could be restored only via username/password.
