### ISSUE TITLE
Elements of Invitation form not visible in night theme

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#367]
We've identified a UI issue related to the Night theme of our application.

Specifically, some elements within the Invitation form are not properly visible when the Night theme is applied. This issue affects user experience and may lead to difficulty in form completion.

To reproduce the issue:

* Apply the Night theme.
* Navigate to the Invitation form.
* Observe that certain form elements are not visible.

We need to adjust the color scheme or styling for these elements in the Night theme to ensure they remain visible and legible to users.
<img width="1289" alt="Screenshot 2023-06-10 at 12 52 13" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/1595061/425fd547-8e64-4dd8-8091-c1d926a13814">

**Comment by tomicvladan** [comment]
@IgorShadurin Do you have svg images for invites? Current images are in png which can't be adjusted. I tried to convert them, but some of them can't be converted, I'm not sure why,
