### ISSUE TITLE
Links in Overview section lead to wrong content

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#374]
Screen in question: https://app.fairdrive.fairdatasociety.org/overview

![image](https://github.com/fairDataSociety/fairdrive-theapp/assets/1554520/0fb17b0c-e013-4dcf-834d-0c817574dd45)

The "Explore Apps" should lead to the Explore section, currently it takes you to the pods list.
The "Join our Ecosystem" should lead to https://fairdataprotocol.bzz.link/ , currently it leads to FairOS docs.

These are probably minor fixes or maybe already handled in another issue. 

@IgorShadurin please triage.

**Comment by IgorShadurin** [comment]
Present in dev. @tomicvladan, can you take it after the current tasks?
