### ISSUE TITLE
Link to Rules for invite leads to 404 page

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#383]
This link "Rules" leads to 404 page:

![image](https://github.com/fairDataSociety/fairdrive-theapp/assets/1554520/18057a43-2204-4662-ac11-2d37fa6ba703)

Link points to: https://app.fairdrive.dev.fairdatasociety.org/invite

App used: https://app.fairdrive.dev.fairdatasociety.org/invite

**Comment by IgorShadurin** [comment]
Fixed by https://github.com/fairDataSociety/fairdrive-theapp/pull/384, but the page needs to be filled with content https://create.dev.fairdatasociety.org/#/bb-rules.

Issue for this: https://github.com/fairDataSociety/fdp-create-account/issues/256
