### ISSUE TITLE
Password protection for wallet creation using Metamask

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#399]
Our group discussions have led to a suggested improvement for our current login mechanism with MetaMask within Fairdrive. As it stands, the creation of a user's wallet is dependent on the signature of the text signed with MetaMask. For an increased measure of security, we propose adding an additional password requirement for the process of creating new wallets.

**Proposed Feature:**

- After the user logs in through MetaMask, the system should prompt the user to input an additional password.
- This password, used together with the MetaMask signature, can facilitate the creation of new wallets.
- Given that a single MetaMask wallet's signature remains constant, introducing variable passwords could allow users to create multiple accounts linked to the same MetaMask wallet by simply changing the password.

This proposed addition could provide a barrier against malicious sites that might attempt to gain unauthorized access to users' accounts using the captured MetaMask signature.

**Points for Consideration:**

- Could we provide an option for users to access their default accounts without the necessity of a password, similar to Trezor's methodology with passphrases and hidden wallets (https://trezor.io/learn/a/passphrases-and-hidden-wallets)?
- What conditions should we apply to create a password? Minimum length? Allowed characters? Requiring special characters?

**Potential Challenges & Solutions:**

- How can we ensure the user has input the correct password? One potential solution could involve checking if pods metadata exists for the account in question. If present, it indicates the account has been used previously and thus the password entered is correct. Conversely, the absence of pods metadata could signify either an incorrect password or an unused account. In such cases, we can notify the user about the absence of metadata and its implications.

@tfius @tomicvladan @crtahlin @tamas6 @asabya

**Comment by tamas6** [comment]
Password:

>   Must be at least 8 characters.
>   Must not be in the list of 100,000 most popular used passwords [(as defined by the CommonPasswords library)](https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10k-most-common.txt)
>   Must not be the same as the username.

WDYM "we can notify the user about the absence of metadata and its implications."

**Comment by IgorShadurin** [comment]
> Password:
> 
> > Must be at least 8 characters.
> > Must not be in the list of 100,000 most popular used passwords [(as defined by the CommonPasswords library)](https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10k-most-common.txt)
> > Must not be the same as the username.
> 
> WDYM "we can notify the user about the absence of metadata and its implications."

If a person entered the password "aaa1" and uploaded the data, then returned to the site a month later and entered the password "aaa2", forgetting what number he set a month ago. So, a person might think his data is gone.
After entering the password, we can check if the data was created before. If there was no data, it means that this is either a new account or the password is entered incorrectly.
In this case, we can display a message like: "No data was found in this account. If this is a new account, just continue. If you have already uploaded data before, then check your password for correctness."

**Comment by tamas6** [comment]
My apologies but, why would anyone think the data is gone?    🔒 

First think will come to their mind, "I forgot my username" 
--> let's help her/him recover it, right?

**Comment by IgorShadurin** [comment]
With metamask and password authentication, there will be no username. The wallet will be deterministically generated on the fly.

If you make a mistake with the password, then a wallet is still generated, but a new one. But with the new wallet, there will be no access to the old data.

**Comment by tamas6** [comment]
> With metamask and password authentication, there will be no username. The wallet will be deterministically generated on the fly.
> 
> If you make a mistake with the password, then a wallet is still generated, but a new one. But with the new wallet, there will be no access to the old data.

I see now this is tricky, we should consider is there even necessity for feature like 1 Metamask acc + Multiple Fairdrive acc, before make it easy to create
 
 correct me if I'm wrong but when  
 **User opens Chrome/Firefox** 
1.)and first login to Metamask, 
 - User wants FairDrive acc without entering FD password (potentially different than MM password)
2.) first wants to enter FD with password to the acc that was previously used through MM 
 - So there is no username input, because through MM and pw auth, username is not initiated
 + or, there is 2 more option: a) conventional Username + pw input,  b) suggest MM login and sync FD && MM register and sync FD 
 
I just have a humble opinion about what user needs, I suggest a poll
