### ISSUE TITLE
Inconsistent margins on the login page footer on mobile devices

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#404]
On the login page of Fairdrive's mobile version, there seems to be an issue with the footer box margins. The left side of the box has a margin, making it asymmetric with the right side, which doesn't have such a margin. 

This inconsistency in the UI can negatively affect the user experience as the design appears unbalanced. I recommend that we should adjust the CSS to make sure both sides have no margins, resulting in a symmetrical and more pleasing appearance.

Steps to reproduce:
1. Open Fairdrive on a mobile device.
2. Navigate to the login page.
3. Observe the footer box.

Expected behavior:
The footer box should have no margins on both sides, providing a balanced and aesthetically pleasing user interface.

Actual behavior:
The left side of the footer box has a margin, while the right side does not, leading to an asymmetrical appearance.

<img width="557" alt="Screenshot 2023-07-21 at 09 42 44" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/1595061/a91ce48a-b0f8-42d0-bcac-8f6acffa00af">

**Comment by tomicvladan** [comment]
The footer has correct spacing. But there is a padding in the layout which pushes the whole page to the right.

https://github.com/fairDataSociety/fairdrive-theapp/blob/292045e61af8be399037af96efe35eda9df6495f/src/components/Layouts/AuthenticationLayout/AuthenticationLayout.tsx#L21C26-L21C30

Is this padding a mistake or is it a part of design?

**Comment by IgorShadurin** [comment]
Oh, by the way, I didn’t pay attention that the header also has padding. Perhaps this is part of the UI for the PC version, most likely it should be there, but for the mobile version, in my opinion, it is better without padding. What do you think about this?

**Comment by tfius** [comment]
if we can detect that we are on mobile, "connect" will not work with mobile wallet or will it ?
