### ISSUE TITLE
Add sorting of files

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#41]
In both the tiles and list view. Make available sorting by:
- [x] date created
- [x] name
- [x] size

**Comment by mmahmutovic** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/commit/b1630b5fe7a8f525ad7e8888e97f3c2ee8508211

Added sorting for desc/asc name, size, type, date created
<img width="384" alt="Screenshot 2021-08-06 at 09 57 22" src="https://user-images.githubusercontent.com/75730861/128477383-4e9b2aa6-8a56-4fe8-8685-54602649aff8.png">
