### ISSUE TITLE
Modal display issue when copying an invite on mobile view (iPhone XR)

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#414]
On the mobile view, specifically on iPhone XR, copying an invite is causing the modal to display in a buggy manner. The modal needs to be fixed to ensure proper rendering and functionality.

https://github.com/fairDataSociety/fairdrive-theapp/assets/1595061/0769e593-4d0b-4d83-bea0-a567e9320590

**Comment by tfius** [comment]
we should think of adding a hamburger menu for left toolbar, it takes so much space,  ?
