### ISSUE TITLE
Reconsideration of Metamask login signature Text

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#429]
During the review of our Metamask login process as defined in the FIP [here](https://github.com/fairDataSociety/FIPs/blob/master/text/0063-external-account-generator.md), a suggestion arose to modify the text of the signature. The proposed change is from 'I am granting FULL ACCESS to the FDP account' to a new text that includes the Ethereum EOA address, for example, 'I am granting FULL ACCESS to the FDP account for address: 0xD94EC0C1BF63AaCff689ADE57bf043E426B8174a'.

This change presents a couple of questions:
1) What should the exact text be for data signing with the EOA address included?
2) How would this modification improve security? Considering a potential scenario where an attacker requests the signature of the text from a fraudulent site. In such a situation, the attacker would already need access to the user's address to request the signature, and thus could easily insert the address into the message. From my perspective, it seems we might not be able to increase security by this change.
3) Could this proposed text change cover other scenarios not related to security?

@tfius

**Comment by tfius** [comment]
1. as you suggested 'I am granting FULL ACCESS to the FDP account for address: 0xUSERADDRESS'.
2. Will not change anything on fraudulent site, they can still phish signature. 
3. This only changes that every user signs different message and not all users same message every time.
