### ISSUE TITLE
Add delete features: file, folder, pod

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#43]
- [x] Delete file
- [ ] Delete folder
- [x] Delete pod

**Comment by mmahmutovic** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/commit/53f31ae4e85886c8105549eeae6e33ad994ef503

Added delete file on side bar and dropdown menu

**Comment by mmahmutovic** [comment]
Need to add buttons and logic to rerender after pod/folder delete
