### ISSUE TITLE
Incorrect branch specified in .github/workflows/buildx.yml file

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#432]
The [.github/workflows/buildx.yml](https://github.com/fairDataSociety/fairdrive-theapp/blob/development/.github/workflows/buildx.yml) file was recently changed in such a way that it runs only on the 'main' branch. However, our repository doesn't have a 'main' branch; we use 'master' as our primary branch. 

This misconfiguration can cause tests to be skipped before merging to 'master' and deploying to production. It's risky because any issues that might be caught by these tests will go unnoticed, potentially leading to unexpected behavior in the production environment.

We need to update the .github/workflows/buildx.yml file to trigger actions on the 'master' branch, not 'main'.

In addition to fixing this specific issue, we should also review recent changes to see if any other modifications could alter the current behavior of our GitHub Actions.

**Comment by tfius** [comment]
did i mess this up ? 
i used development buildx.yml

**Comment by IgorShadurin** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/pull/441
