### ISSUE TITLE
Add support for Metamask Mobile

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#433]
Currently, our implementation only supports login with the Metamask Chrome extension. To broaden our user base and improve user experience, I propose implementing support for Metamask Mobile. 

This will involve integrating the Metamask SDK into our app, which will provide additional authentication options such as using a mobile device or a PC without a Chrome extension but using a QR code, among other features. 

This feature will need thorough testing across various scenarios and environments. Here are some test cases to consider:

- Login with wallets that are not connected to the site.
- Login with wallets that are already connected to the site.
- Login in incognito mode.
- Testing in mobile browsers with the same cases.
- Test login with QR code.
- Test across different browsers.

**Comment by tfius** [comment]
How much effort would this require ?

**Comment by IgorShadurin** [comment]
I'm trying to do this. At first glance, everything seems simple, but in fact, there are problems in some cases with the mobile version. I'm trying out different approaches.

**Comment by IgorShadurin** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/pull/443
