### ISSUE TITLE
Can't create new pods

### ISSUE THREAD

**Issue by teardrop** [fairDataSociety/fairdrive-theapp#449]
Summary: When creating a new pod I get an error

Steps to reproduce:
1. Click on Create Pod in side bar
2. Name your pod
3. click Create Pod button

Result:
get error message "Error: Account wallet not found"

Expected:
Pod is created

System data:
URL: https://app.fairdrive.dev.fairdatasociety.org/drive
browser: Chrome for Mac OS Version 115.0.5790.170 (Official Build) (arm64)

<img width="1461" alt="Cursor_and_Fairdrive" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/898007/eb9dbab6-c84e-4805-a3aa-aec16fd0eb69">

**Comment by IgorShadurin** [comment]
Should be fixed after merging https://github.com/fairDataSociety/fairdrive-theapp/pull/448

**Comment by teardrop** [comment]
Fixed.
Tested on https://app.fairdrive.dev.fairdatasociety.org/drive
