### ISSUE TITLE
Error in Invite Form with Blossom Extension

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairdrive-theapp#459]
I encountered an error while trying to access the Invite section after logging into Fairdrive using the Blossom extension.

When attempting to visit the Invite section, I'm faced with the following error message: "Application error: a client-side exception has occurred (see the browser console for more information)."

### Expected Behavior

The application should handle this situation gracefully, either by providing a more descriptive error message to the user or by avoiding the error altogether.

### Steps to Reproduce

1. Log in to Fairdrive using the Blossom extension.
2. Attempt to visit the Invite section.
3. Observe the error message.

<img width="1725" alt="Screenshot 2023-08-24 at 13 35 09" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/1595061/85af2ed6-b159-45b2-9a1d-c2d20afdc808">

**Comment by tomicvladan** [comment]
This error occurres because Fairdrive cannot access wallet object when the user is logged in with Blossom. This page needs to be modified to support Blossom usage.
