### ISSUE TITLE
Prepare proposal how Dapps should be started from Fairdrive (technically)

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#46]
Your opinion/solution on how opening an app from Fairdrive should take place. High/medium level, do not go into implementation.

**Comment by mmahmutovic** [comment]
[Untitled document.docx](https://github.com/fairDataSociety/fairdrive-theapp/files/6995704/Untitled.document.docx)

**Comment by mmahmutovic** [comment]
[Opening apps from Fairdrive.docx](https://github.com/fairDataSociety/fairdrive-theapp/files/6995705/Opening.apps.from.Fairdrive.docx)

<img width="326" alt="Screenshot 2021-08-17 at 00 09 15" src="https://user-images.githubusercontent.com/75730861/129636425-90290bb9-d257-40bd-90e8-d9ce0a80174c.png">
