### ISSUE TITLE
Could not receive share code!

### ISSUE THREAD

**Issue by teardrop** [fairDataSociety/fairdrive-theapp#460]
Summary: When I'm trying to share a file, there is no code to copy. Console says "Could not receive share code!"

Steps to reproduce:

1. Open a file stored in Fairdrive
2. Click on the ellipsis
3. Select Share

Result:
- observe no sharing code
- console error message is "Could not receive share code!"

Expected:
Share URL/code is displayed

System data:
URL: https://app.fairdrive.dev.fairdatasociety.org/drive
browser: Chrome for Mac OS Version 115.0.5790.170 (Official Build) (arm64)
<img width="1462" alt="Fairdrive" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/898007/5afaddc7-6898-40ef-86b5-621531aa7d2b">

**Comment by IgorShadurin** [comment]
It should work; however, the UX of this modal should be improved. https://github.com/fairDataSociety/fairdrive-theapp/issues/462
