### ISSUE TITLE
Add feature: Text preview option (like for photos, video)

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#47]
Like for photos in the right hand sidebar, but in this case for text/markdown.

**Comment by mmahmutovic** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/commit/176790e8c82a37937c31e263cad198e70494a2f2

![Screenshot 2021-08-06 at 18 34 21](https://user-images.githubusercontent.com/75730861/128542958-901c16a6-cf77-4bc4-a445-1f96a82258cd.png)


And edited all icons to be showed by type
![Screenshot 2021-08-06 at 18 34 25](https://user-images.githubusercontent.com/75730861/128542984-137e5573-08fe-4d6d-840a-41be223df7c3.png)
