### ISSUE TITLE
Import function hide from header

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fairdrive-theapp#478]
**Old issue was about the ui error at ipad mini**

<img width="570" alt="ipad mini" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/81620050/38ebceb8-7274-4f1f-9e54-8e3945dbb45e">

tilting solves this bt.

Other devices are ok.

**Comment by tamas6** [comment]
### Let's hide the import button until further notice.

**Comment by tomicvladan** [comment]
It has been removed here https://github.com/fairDataSociety/fairdrive-theapp/pull/518
