### ISSUE TITLE
when in folder, if one presses on pod, it goes directly to root of pod

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fairdrive-theapp#502]
![image](https://github.com/fairDataSociety/fairdrive-theapp/assets/1674145/85be9c73-7297-4ff1-ac07-ebae02e9a8b8)

also < could be removed, and command be added to 'pod dropdown'

**Comment by tomicvladan** [comment]
If this feature got disabled, then there wouldn't be a way to get back to root directory.
