### ISSUE TITLE
Reduce space in file list on mobile

### ISSUE THREAD

**Issue by tomicvladan** [fairDataSociety/fairdrive-theapp#504]
The new design on mobile screen size should look as following:

![photo_2023-09-14_13-03-19](https://github.com/fairDataSociety/fairdrive-theapp/assets/15090003/cee466a5-387b-49bc-883a-c2b1f9b900e8)

**Comment by tomicvladan** [comment]
Although this design looks nice, there are several issues that are difficult to solve.

1. Reducing space between files and removing page padding make some new problems. The file/folder dropdown is defined in this line of code https://github.com/fairDataSociety/fairdrive-theapp/blob/1e9982570f75a585adb11728efed242892a0cd07/src/components/Dropdowns/DriveItemDropdown/DriveItemMenu.tsx#L150. Because it must be absolute positioned, it's left value is set to -8rem. This works fine when there is enough space on the left and right side. But when the space is reduced, the menu gets cut off by page. Same happens on the right side. There are some solutions that describe usage of the Float component https://github.com/tailwindlabs/headlessui/issues/30, but I couldn't make it work.
2. On a smaller screen size, there is no enough space to line up all navigation buttons on the top.

@tfius @IgorShadurin @tamas6  What's your opinion, how to solve these problems?

**Comment by tomicvladan** [comment]
![Screenshot from 2023-09-14 14-14-56](https://github.com/fairDataSociety/fairdrive-theapp/assets/15090003/ea1ee4f6-2c71-4caf-a2d4-6c23fe12509c)

**Comment by tomicvladan** [comment]
Here are some screenshots of the current state. Please tell me what you think @tamas6 @IgorShadurin @tfius 

 
![Screenshot from 2023-09-15 16-00-32](https://github.com/fairDataSociety/fairdrive-theapp/assets/15090003/9b7dab39-1277-4f93-953f-2cf4854c3808)
![Screenshot from 2023-09-15 16-01-17](https://github.com/fairDataSociety/fairdrive-theapp/assets/15090003/7bbc294c-b900-4ee2-8487-7fed3b976ceb)

**Comment by tamas6** [comment]
Promising, once we should separate "drive" from the others, cause they are far from equal on features

**Comment by tfius** [comment]
what does second picture mean?
first pic looka good
