### ISSUE TITLE
Uploading a file - need error message when not in folder

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fairdrive-theapp#506]
![14762419-7D96-4F4F-855E-0AB03BC4875A_1_201_a](https://github.com/fairDataSociety/fairdrive-theapp/assets/81620050/74cc8907-3b32-41cb-a6a5-5144be1fd87b)

let's you select a file, but then it follows a blank page shown above.

**Comment by tamas6** [comment]
Suggestion: When inside drive but not in folder, "Upload" shouldn't appear on slide. @tomicvladan

**Comment by tfius** [comment]
not on side, just reduce padding. dont change flow in layout.

**Comment by tomicvladan** [comment]
I think it's better to just disable it. If the user clicks it, then a toolbar can appear letting the user know that a pod must be selected first?

**Comment by tamas6** [comment]
> I think it's better to just disable it. If the user clicks it, then a toolbar can appear letting the user know that a pod must be selected first?

I'd expect this behaviour as well.

**Comment by tamas6** [comment]
in this case worth to mention #479

**Comment by tomicvladan** [comment]
The button is from now on disabled when there is no pod selected.
