### ISSUE TITLE
1. Intro Component "First-time use to second-time use Flow" 

### ISSUE THREAD

**Issue by sydneyspracklen** [fairDataSociety/fairdrive-theapp#60]
https://user-images.githubusercontent.com/88720078/128868177-d4441ea9-197b-47dc-8ed2-7e8626d32caf.mov

The amount of space the "intro" component takes upon first-time use. We solved that by, creating a "2nd-time use" component that greatly reduces the amount of vertical height that is being taken up.  Video recording of how that works, plus a link to the flow prototype plus a link to page and frame this new design component is on will be included. 
See below links:

**Link to design component in design system:** https://www.figma.com/file/1uwKXyizhv88JvDckja7Py/Fairdrive-Main?node-id=1%3A1228

**Link to Flow Prototype:** https://www.figma.com/proto/1uwKXyizhv88JvDckja7Py/Fairdrive-Main?node-id=1952%3A46700&scaling=scale-down-width&page-id=350%3A9615&starting-point-node-id=1952%3A46685&show-proto-sidebar=1

**Comment by mmahmutovic** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/commit/6ef8201ad0c41a6f15df85b62b46be22c683590d

<img width="1077" alt="Screenshot 2021-08-16 at 11 16 36" src="https://user-images.githubusercontent.com/75730861/129541260-02f4ad54-8b74-459f-8602-3f27e1260142.png">
<img width="1113" alt="Screenshot 2021-08-16 at 11 16 43" src="https://user-images.githubusercontent.com/75730861/129541264-cedb9683-ceff-4f90-a7e4-4d1edfe0a1c9.png">
