### ISSUE TITLE
2. Search Results "Search flow" 

### ISSUE THREAD

**Issue by sydneyspracklen** [fairDataSociety/fairdrive-theapp#61]
https://user-images.githubusercontent.com/88720078/128868522-4682f61b-0310-40c6-86ce-cc218fe94035.mov

2. Search Results "Search flow" 

Here we noted that the specific states for the search input field were not put into development, those should be put in - those states can be seen in the design system and/or in the prototype. We solved this general problem of what happens when a user searches by including a new section in the main part of the screen which emphasises the search query result. This is called the search query component. The component can be found in the design system and vid recording of how it works will be included below:

**Link to all Search components in design system:** https://www.figma.com/file/1uwKXyizhv88JvDckja7Py/Fairdrive-Main?node-id=1953%3A78207

**Link to Frames within the prototype:** https://www.figma.com/file/1uwKXyizhv88JvDckja7Py/Fairdrive-Main?node-id=1937%3A56554

**Comment by mmahmutovic** [comment]
https://github.com/fairDataSociety/fairdrive-theapp/commit/6ef8201ad0c41a6f15df85b62b46be22c683590d

<img width="1077" alt="Screenshot 2021-08-16 at 11 16 36" src="https://user-images.githubusercontent.com/75730861/129541260-02f4ad54-8b74-459f-8602-3f27e1260142.png">
<img width="1113" alt="Screenshot 2021-08-16 at 11 16 43" src="https://user-images.githubusercontent.com/75730861/129541264-cedb9683-ceff-4f90-a7e4-4d1edfe0a1c9.png">

**Comment by mmahmutovic** [comment]
![Uploading Screenshot 2021-08-16 at 11.17.02.png…]()
