### ISSUE TITLE
Importing of shared files does not work as expected

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#67]
Someone shared a link to a file in Fairdrive with me.

I tried adding it.
1. the modal for import it does not close, after import; you have to close it manually
2. the file was in the list for a brief time in view, but then I think the files were resorted it was gone
3. also, i swithed to the list view, and it's all garbled up; only on the second adding, it apeared in the List view

and the list view itself does not show 5 rows as in settings, but more:
![image](https://user-images.githubusercontent.com/1554520/132699072-a6cf50da-a293-41c4-8e59-c6646d01417a.png)

**Comment by AngelaVitzthum** [comment]
These issues are resolved. Will open a new issue if needed in future.
