### ISSUE TITLE
Sharing of pods

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairdrive-theapp#68]
Importing a Pod flow does not seem to go trough. I generate a link from upper right menu (which should specifically say that a pod is to be shared, currently says I will share "material", which is very vague) .

![image](https://user-images.githubusercontent.com/1554520/133631689-f40e7538-e8d8-477b-aa7d-677d22b55f78.png)

Trying to import it in another account and nothing seems to happen - the window stays open.

![image](https://user-images.githubusercontent.com/1554520/133631911-091acfa7-802a-42af-8920-4a99d37e867e.png)

**Comment by AngelaVitzthum** [comment]
Fixed.
