### ISSUE TITLE
ConfirmMnemonic.tsx: Mnemonic confirmation should be random

### ISSUE THREAD

**Issue by molekilla** [fairDataSociety/fairdrive-theapp#91]
Right now is hardcoded

```
const ConfirmMnemonic: FC<ConfirmMnemonicProps> = () => {
  const { register, handleSubmit, formState } = useForm();
  const { setUser, setPassword, setAddress } = useContext(UserContext);
  const { clearPodContext } = useContext(PodContext);
  const { errors } = formState;

  const [errorMessage, setErrorMessage] = useState('');

  const onSubmit = (data: {
    'word-5': string;
    'word-11': string;
    'word-12': string;
  }) => {

...
```
https://github.com/fairDataSociety/fairdrive-theapp/blob/8fb556ebf93cf99d89bb8223abd39e82214a5f0e/src/components/Forms/ConfirmMnemonic/ConfirmMnemonic.tsx#L26

There is also some issues with backend and/or mnemonic verification that sometimes it fails but manages to navigate to the next route

**Comment by crtahlin** [comment]
Please check if still relevant with current login and close with comment if not @molekilla .
