### ISSUE TITLE
User registration in Fairdrive fails in Safari browser

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fairdrive-theapp#94]
### Error at 3 security word validation

<img width="400" alt="Screenshot 2022-05-22 at 22 46 12" src="https://user-images.githubusercontent.com/81620050/169715571-5638f829-7d79-43a4-b10d-151922db6775.png">

**Comment by AngelaVitzthum** [comment]
**Additional Info**

- _User Browser_: Safari
- _User Device Type_: MBP 15" i7
- User was able to get login to work on Chrome

**Comment by tfius** [comment]
Is anyone looking into this ?

**Comment by crtahlin** [comment]
@molekilla please check if registration is still failing in Safari.

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fair-Data-Protocol-61f37a061754030017d022ea/issues/fairDataSociety/fairdrive-theapp/94?planning-poker) with ZenHub @tfius @molekilla

**Comment by tfius** [comment]
user registration and account creation shoul and mus go to create-account app so we dont have to do double checking, infrastructure changes and support. all apps should point to create account app. also migration should be done there for 4 months (we offer account support after v2 launch)

**Comment by molekilla** [comment]
Need the url to add to react env vars

**Comment by molekilla** [comment]
@tfius https://github.com/fairDataSociety/fairdrive-theapp/pull/115

**Comment by crtahlin** [comment]
From meeting: Not in scope, as registration will move out of Fairdrive.
